library("sqldf")
ABL.sub <- sqldf("select * from monthly where Well_N like 'ABL%'")
ABL.sub <- droplevels(ABL.sub)
AUKS.sub <- sqldf("select * from monthly where Well_N like 'AUKS%'")
AUKS.sub <- droplevels(AUKS.sub)
ANTK.sub <- sqldf("select * from monthly where Well_N like 'ANTK%'")
ANTK.sub <- droplevels(ANTK.sub)
LIZ.sub <- sqldf("select * from monthly where Well_N like 'LIZ%'")
LIZ.sub <- droplevels(LIZ.sub)
VEZ.sub <- sqldf("select * from monthly where Well_N like 'VEZ%'")
VEZ.sub <- droplevels(VEZ.sub)
ZAD.sub <- sqldf("select * from monthly where Well_N like 'ZAD%'")
ZAD.sub <- droplevels(ZAD.sub)
GRK.sub <- sqldf("select * from monthly where Well_N like 'GRK%'")
GRK.sub <- droplevels(GRK.sub)
KRT.sub <- sqldf("select * from monthly where Well_N like 'KRT%'")
KRT.sub <- droplevels(KRT.sub)
NSD.sub <- sqldf("select * from monthly where Well_N like 'NSD%'")
NSD.sub <- droplevels(NSD.sub)
GEN.sub <- sqldf("select * from monthly where Well_N like 'GEN%'")
GEN.sub <- droplevels(GEN.sub)
