library(grid)

mastervp <- viewport(w=unit(24, "inches"), h=unit(36, "inches"))
pushViewport(mastervp)
grid.rect(gp=gpar(lty="dashed"))
dtuwellprodchart(Nausodis, "NSD1")
dtuwellprodchart(Nausodis, "NSD3R")
dtuwellprodchart(Nausodis, "NSD5")
dtuwellprodchart(Nausodis, "NSD6")
dtuwellprodchart(Nausodis, "NSD7")
dtuwellprodchart(Nausodis, "NSD8")
dtuwellprodchart(Nausodis, "NSD9")
dtuwellprodchart(Nausodis, "NSD10")
dtuwellprodchart(Nausodis, "NSD11")
dtuwellprodchart(Nausodis, "NSD12")
dtuwellprodchart(Nausodis, "NSD13")
dtuwellprodchart(Nausodis, "NSD14")
dtuwellprodchart(Nausodis, "NSD15")
dtuwellinjchart(Nausodis, "NSD1")
dtuwellinjchart(Nausodis, "NSD7")
dtufieldprodchart(NSD.sub)
