#loading required libraries
library(data.table)
library(ggplot2)
library(grid)
library(magrittr)
library(dplyr)
library(gtable)
library(ggthemes)
library(gridBase)
library(png)
library(gridExtra)
library(scales)

Nausodis <- NSD.sub
Nausodis <- setkey(setDT(Nausodis), Date_m, Well_N)[
  CJ(Date_m=seq(min(Date_m), max(Date_m), by='1 month'),
     Well_N=unique(Well_N))][is.na(QOM), QOM:=0][is.na(QWM), QWM:=0][is.na(QFM), QFM:=0][is.na(QIW), QIW:=0][is.na(QOD), QOD:=0][is.na(QWD), QWD:=0][is.na(QFD), QFD:=0][order(Well_N)]

mindate <- min(as.Date(Nausodis$Date_m))
minyear <- year(mindate)+1
minlab <- as.Date(paste(minyear, 01, 01, sep = "-"))
maxdate <- max(as.Date(Nausodis$Date_m))
maxyear <- year(maxdate)
maxlab <- as.Date(paste(maxyear, 01, 01, sep = "-"))

Nausodis <- Nausodis[order(as.Date(Nausodis$Date_m, format="%Y-%m-%d")),]
Nausodis = Nausodis %>% group_by(Well_N) %>% mutate(CumOil=cumsum(QOM))
Nausodis = Nausodis %>% group_by(Well_N) %>% mutate(CumWat=cumsum(QWM))
Nausodis = Nausodis %>% group_by(Well_N) %>% mutate(CumF=cumsum(QFM))
Nausodis = Nausodis %>% group_by(Well_N) %>% mutate(CumInj=cumsum(QIW))
Nausodis = Nausodis %>% group_by(Date_m) %>% mutate(QOMF = sum(QOM))
Nausodis = Nausodis %>% group_by(Date_m) %>% mutate(QWMF = sum(QWM))
Nausodis = Nausodis %>% group_by(Well_N) %>% mutate(CumOilF=cumsum(QOMF))

pdf("overview-charts/Nausodis.pdf", width = 23, height = 3)
# Charting (calling external function)
grid.newpage()
pushViewport(viewport(layout = grid.layout(16,1)))
vplayout <- function(x,y)
  viewport(layout.pos.row = x, layout.pos.col = y)
pnsd1 <- dtuwellprodchartow(Nausodis, "NSD1")
pnsd3r <- dtuwellprodchartow(Nausodis, "NSD3R")
pnsd5 <- dtuwellprodchartow(Nausodis, "NSD5")
pnsd6 <- dtuwellprodchartow(Nausodis, "NSD6")
pnsd7 <- dtuwellprodchartow(Nausodis, "NSD7")
pnsd8 <- dtuwellprodchartow(Nausodis, "NSD8")
pnsd9 <- dtuwellprodchartow(Nausodis, "NSD9")
pnsd10 <- dtuwellprodchartow(Nausodis, "NSD10")
pnsd11 <- dtuwellprodchartow(Nausodis, "NSD11")
pnsd12 <- dtuwellprodchartow(Nausodis, "NSD12")
pnsd13 <- dtuwellprodchartow(Nausodis, "NSD13")
pnsd14 <- dtuwellprodchartow(Nausodis, "NSD14")
pnsd15 <- dtuwellprodchartow(Nausodis, "NSD15")
pnsd16 <- dtuwellprodchartow(Nausodis, "NSD16")
fprod <- dtufieldprodchartow(Nausodis)
print(pnsd1, vp = vplayout(1,1))
print(pnsd3r, vp = vplayout(2,1))
print(pnsd5, vp = vplayout(3,1))
print(pnsd6, vp = vplayout(4,1))
print(pnsd7, vp = vplayout(5,1))
print(pnsd8, vp = vplayout(6,1))
print(pnsd9, vp = vplayout(7,1))
print(pnsd10, vp = vplayout(8,1))
print(pnsd11, vp = vplayout(9,1))
print(pnsd12, vp = vplayout(10,1))
print(pnsd13, vp = vplayout(11,1))
print(pnsd14, vp = vplayout(12,1))
print(pnsd15, vp = vplayout(13,1))
print(pnsd16, vp = vplayout(14,1))
print(fprod, vp = vplayout(15,1))

dev.off()
