#loading required libraries
library(data.table)
library(ggplot2)
library(grid)
library(magrittr)
library(dplyr)
library(gtable)
library(ggthemes)
library(gridBase)
library(png)
library(gridExtra)
library(scales)

Vezaiciai <- VEZ.sub
Vezaiciai <- setkey(setDT(Vezaiciai), Date_m, Well_N)[
  CJ(Date_m=seq(min(Date_m), max(Date_m), by='1 month'),
     Well_N=unique(Well_N))][is.na(QOM), QOM:=0][is.na(QWM), QWM:=0][is.na(QFM), QFM:=0][is.na(QIW), QIW:=0][is.na(QOD), QOD:=0][is.na(QWD), QWD:=0][is.na(QFD), QFD:=0][order(Well_N)]

mindate <- min(as.Date(Vezaiciai$Date_m))
minyear <- year(mindate)+1
minlab <- as.Date(paste(minyear, 01, 01, sep = "-"))
maxdate <- max(as.Date(Vezaiciai$Date_m))
maxyear <- year(maxdate)
maxlab <- as.Date(paste(maxyear, 01, 01, sep = "-"))

Vezaiciai <- Vezaiciai[order(as.Date(Vezaiciai$Date_m, format="%Y-%m-%d")),]
Vezaiciai = Vezaiciai %>% group_by(Well_N) %>% mutate(CumOil=cumsum(QOM))
Vezaiciai = Vezaiciai %>% group_by(Well_N) %>% mutate(CumWat=cumsum(QWM))
Vezaiciai = Vezaiciai %>% group_by(Well_N) %>% mutate(CumF=cumsum(QFM))
Vezaiciai = Vezaiciai %>% group_by(Well_N) %>% mutate(CumInj=cumsum(QIW))
Vezaiciai = Vezaiciai %>% group_by(Date_m) %>% mutate(QOMF = sum(QOM))
Vezaiciai = Vezaiciai %>% group_by(Date_m) %>% mutate(QWMF = sum(QWM))
Vezaiciai = Vezaiciai %>% group_by(Well_N) %>% mutate(CumOilF=cumsum(QOMF))

pdf("overview-charts/Vezaiciai.pdf", width = 23, height = 3)
# Charting (calling external function)
grid.newpage()
pushViewport(viewport(layout = grid.layout(15,1)))
vplayout <- function(x,y)
  viewport(layout.pos.row = x, layout.pos.col = y)
pvez4 <- dtuwellprodchartow(Vezaiciai, "VEZ4")
pvez11 <- dtuwellprodchartow(Vezaiciai, "VEZ11")
pvez12 <- dtuwellprodchartow(Vezaiciai, "VEZ12")
pvez13 <- dtuwellprodchartow(Vezaiciai, "VEZ13")
pvez13r <- dtuwellprodchartow(Vezaiciai, "VEZ13R")
pvez14 <- dtuwellprodchartow(Vezaiciai, "VEZ14")
pvez15 <- dtuwellprodchartow(Vezaiciai, "VEZ15")
pvez16 <- dtuwellprodchartow(Vezaiciai, "VEZ16")
pvez17 <- dtuwellprodchartow(Vezaiciai, "VEZ17")
pvez18 <- dtuwellprodchartow(Vezaiciai, "VEZ18")
pvez19 <- dtuwellprodchartow(Vezaiciai, "VEZ19")
pvez15r1 <- dtuwellprodchartow(Vezaiciai, "VEZ15R1")
pvez16r1 <- dtuwellprodchartow(Vezaiciai, "VEZ16R1")
pvez20 <- dtuwellprodchartow(Vezaiciai, "VEZ20")
fprod <- dtufieldprodchartow(Vezaiciai)
print(pvez4, vp = vplayout(1,1))
print(pvez11, vp = vplayout(2,1))
print(pvez12, vp = vplayout(3,1))
print(pvez13, vp = vplayout(4,1))
print(pvez13r, vp = vplayout(5,1))
print(pvez14, vp = vplayout(6,1))
print(pvez15, vp = vplayout(7,1))
print(pvez16, vp = vplayout(8,1))
print(pvez17, vp = vplayout(9,1))
print(pvez18, vp = vplayout(10,1))
print(pvez19, vp = vplayout(11,1))
print(pvez15r1, vp = vplayout(12,1))
print(pvez16r1, vp = vplayout(13,1))
print(pvez20, vp = vplayout(14,1))
print(fprod, vp = vplayout(15,1))

dev.off()
